import { ACTION_IDS, MODULE_IDS, type AccessActor, type ActionId, type ModuleId, type StaffPermissions } from '../types/access';
export const MODULE_LABELS: Record<ModuleId, string> = { dashboard: 'Trang chủ', rooms: 'Sơ đồ phòng', reservations: 'Đặt phòng', stays: 'Khách đang ở', sales: 'Bán vé / khách ngoài', debt: 'Quản lý công nợ', analytics: 'Thống kê doanh thu', reports: 'Xuất Excel / PDF', services: 'Bảng giá & Dịch vụ' };
export const ACTION_LABELS: Record<ActionId, string> = { 'booking.create': 'Tạo đặt phòng', 'booking.cancel': 'Hủy đặt phòng (giữ lịch sử và cọc)', 'booking.archive': 'Lưu trữ phiếu đã hủy, không có cọc', 'stay.checkin': 'Nhận phòng', 'stay.checkout': 'Trả phòng và lập phiếu thu', 'stay.guests': 'Cập nhật khách đi cùng', 'stay.service.add': 'Thêm dịch vụ vào phòng', 'stay.service.remove': 'Xóa dịch vụ chưa thanh toán', 'room.clean': 'Cập nhật tình trạng dọn phòng', 'room.status': 'Cập nhật trạng thái phòng', 'room.configure': 'Thêm/sửa phòng và giá phòng', 'room.delete': 'Xóa phòng chưa có dữ liệu liên quan', 'service.configure': 'Thêm/sửa dịch vụ và đơn giá', 'service.delete': 'Xóa dịch vụ chưa được sử dụng', 'sale.create': 'Bán vé và dịch vụ khách ngoài', 'debt.collect': 'Ghi nhận thu công nợ', 'data.export': 'Xuất Excel / PDF và tải bản sao lưu', 'data.restore': 'Khôi phục dữ liệu (chỉ quản lý)' };
const actionViews: Record<ActionId, ModuleId[]> = { 'booking.create': ['reservations', 'rooms'], 'booking.cancel': ['reservations'], 'booking.archive': ['reservations'], 'stay.checkin': ['stays', 'rooms', 'reservations'], 'stay.checkout': ['stays', 'rooms'], 'stay.guests': ['stays', 'rooms'], 'stay.service.add': ['stays', 'rooms'], 'stay.service.remove': ['stays', 'rooms'], 'room.clean': ['rooms'], 'room.status': ['rooms'], 'room.configure': ['rooms', 'services'], 'room.delete': ['rooms', 'services'], 'service.configure': ['services'], 'service.delete': ['services'], 'sale.create': ['sales'], 'debt.collect': ['debt'], 'data.export': ['reports'], 'data.restore': ['reports'] };
export const DEFAULT_STAFF_PERMISSIONS: StaffPermissions = { views: ['rooms', 'reservations', 'stays', 'sales', 'services'], actions: ['booking.create', 'booking.cancel', 'booking.archive', 'stay.checkin', 'stay.checkout', 'stay.guests', 'stay.service.add', 'room.clean', 'sale.create'] };
export const ACTION_VIEWS = actionViews;
export const ADMIN_ACTOR: AccessActor = { id: 'admin', role: 'ADMIN', username: 'admin', displayName: 'Quản lý', permissions: { views: [...MODULE_IDS], actions: [...ACTION_IDS] }, version: 1 };
export function validatePermissions(input: unknown): StaffPermissions {
  if (!input || typeof input !== 'object') throw new Error('Quyền truy cập không hợp lệ.');
  const p = input as StaffPermissions;
  if (!Array.isArray(p.views) || !Array.isArray(p.actions) || p.views.some(v => !MODULE_IDS.includes(v)) || p.actions.some(v => !ACTION_IDS.includes(v)) || p.actions.includes('data.restore')) throw new Error('Quyền truy cập không hợp lệ.');
  return { views: [...new Set(p.views)], actions: [...new Set(p.actions)] };
}
export function canView(actor: AccessActor, module: string) { return actor.role === 'ADMIN' || actor.permissions.views.includes(module as ModuleId); }
export function canAct(actor: AccessActor, action: ActionId) { return actor.role === 'ADMIN' || (action !== 'data.restore' && actor.permissions.actions.includes(action) && actionViews[action].some(v => canView(actor, v))); }
export function requireAction(actor: AccessActor, action: ActionId) { if (!canAct(actor, action)) throw new Error('Bạn chưa được cấp quyền thực hiện thao tác này.'); }
export function firstAllowedModule(actor: AccessActor): ModuleId | undefined { return MODULE_IDS.find(v => canView(actor, v)); }
