import assert from 'node:assert/strict';
import { copyFileSync } from 'node:fs';
import { createBrowserCLI } from './browser-cli.mjs';
import { loginBrowser } from './browser-auth.mjs';

const run = createBrowserCLI('sonngoc-login-review');
const evaluate = js => run('eval', js);
const settle = () => run('wait', '500');
const check = (js, label) => { assert.equal(evaluate(`(async()=>Boolean(${js}))()`), 'true', label); console.log('PASS', label); };
const screenshot = name => { const output = run('screenshot'); const path = output.match(/Screenshot saved to (.+)/)?.[1]?.trim(); if (path) copyFileSync(path, `.review/${name}.png`); };
const logout = () => {
  evaluate(`document.querySelector('button[aria-label="Ẩn hiện menu"]').click()`);settle();
  run('click', 'aside button[aria-label="Đăng xuất"]');settle();
};
run('close');
run('open', process.env.LOGIN_TEST_URL || 'http://localhost:3000');settle();
evaluate(`sessionStorage.removeItem('son_ngoc_login_session_v1')`);
run('reload');settle();
run('errors', '--clear');
check(`document.getElementById('login-password') && !document.querySelector('header, aside') && !document.querySelector('vite-error-overlay')`, 'login gate hides the management app before authentication');
const beforeData = evaluate(`localStorage.getItem('son_ngoc_hotel_data_v3')`);
for (const [width, height] of [[1440, 920], [320, 740], [375, 812], [768, 900]]) {
  run('set', 'viewport', String(width), String(height));
  check(`document.documentElement.scrollWidth===innerWidth && document.querySelector('form button[type="submit"]').getBoundingClientRect().right<=innerWidth`, `login fits ${width}px`);
  screenshot(`login-${width}`);
}
run('set', 'viewport', '375', '812');
run('fill', '#login-password', 'incorrect');
run('click', 'form button[type="submit"]');settle();
check(`document.querySelector('#login-error')?.innerText.includes('Mật khẩu chưa đúng') && !document.querySelector('header')`, 'incorrect password is rejected with a visible error');
run('click', 'button[aria-label="Hiện mật khẩu"]');
check(`document.querySelector('#login-password').type==='text'`, 'password visibility can be enabled');
run('click', 'button[aria-label="Ẩn mật khẩu"]');
check(`document.querySelector('#login-password').type==='password'`, 'password can be hidden again');
evaluate(`window.__promptCalls=0;const event=new Event('beforeinstallprompt');event.prompt=async()=>{window.__promptCalls++};event.userChoice=Promise.resolve({outcome:'dismissed',platform:'web'});dispatchEvent(event)`);
loginBrowser(run);
check(`document.querySelector('header') && !document.getElementById('login-password')`, 'correct password opens the system');
evaluate(`document.querySelector('button[aria-label="Ẩn hiện menu"]').click()`);settle();
run('click', 'aside button[aria-label="Cài ứng dụng"]');settle();
check(`window.__promptCalls===1 && !document.querySelector('[aria-label="Hướng dẫn cài ứng dụng"]')`, 'installation prompt survives transition from login to dashboard');
evaluate(`document.querySelector('button[aria-label="Ẩn hiện menu"]').click()`);settle();
run('reload');settle();
check(`document.querySelector('header') && !document.getElementById('login-password')`, 'session survives a reload without storing the password');
check(`!sessionStorage.getItem('son_ngoc_login_session_v1').includes('Trinh')`, 'session contains timestamps rather than the password');
logout();
check(`document.getElementById('login-password') && !document.querySelector('header') && !sessionStorage.getItem('son_ngoc_login_session_v1')`, 'logout returns to the login screen and clears the session');
assert.equal(evaluate(`localStorage.getItem('son_ngoc_hotel_data_v3')`), beforeData, 'logout preserves hotel data');
console.log('PASS logout preserves hotel data');
evaluate(`sessionStorage.setItem('son_ngoc_login_session_v1', JSON.stringify({version:1,issuedAt:Date.now()-13*3600000,expiresAt:Date.now()-3600000}))`);
run('reload');settle();
check(`document.getElementById('login-password') && !document.querySelector('header')`, 'expired session requires another login');
evaluate(`Object.defineProperty(window.crypto,'subtle',{configurable:true,value:undefined})`);
loginBrowser(run);
check(`document.querySelector('header')`, 'login also works on LAN browsers without SubtleCrypto');
logout();
run('set', 'device', 'iPhone 14');
run('reload');settle();
run('click', 'button[aria-label="Cài ứng dụng"]');settle();
check(`document.querySelector('[aria-label="Hướng dẫn cài ứng dụng"]')?.textContent.includes('Safari trên iPhone') && document.querySelector('[aria-label="Hướng dẫn cài ứng dụng"] img').getAttribute('src')==='/icon.svg'`, 'iPhone installation guide is available before login with the system logo');
screenshot('login-iphone-install');
run('click', 'button[aria-label="Đóng hướng dẫn cài ứng dụng"]');
check(`document.documentElement.scrollWidth===innerWidth`, 'iPhone login screen does not overflow');
check(`(await (async()=>{const manifest=await fetch('/manifest.json').then(r=>r.json());for(const item of manifest.icons.filter(i=>i.type==='image/png')){const img=new Image();img.src=item.src;await img.decode();if(img.naturalWidth!==Number(item.sizes.split('x')[0]))return false;}const apple=new Image();apple.src=document.querySelector('link[rel="apple-touch-icon"]').href;await apple.decode();return manifest.display==='standalone'&&manifest.start_url==='/'&&apple.naturalWidth===180})())`, 'PWA and iPhone home-screen icons load at their declared sizes');
assert.equal(run('errors'), '', 'no runtime errors in login and installation flows');
console.log('Login and home-screen installation checks passed.');
