import { writeFileSync, mkdirSync } from 'node:fs';
import { createBrowserCLI } from './browser-cli.mjs';
import { loginBrowser } from './browser-auth.mjs';
import assert from 'node:assert/strict';
mkdirSync('.review', {recursive:true});
const run = createBrowserCLI('sonngoc-flow-review');
const evaluate = js => run('eval',js);
const settle = () => run('wait','300');
const click = (selector,text) => { evaluate(`Array.from(document.querySelectorAll(${JSON.stringify(selector)})).find(e=>e.textContent.includes(${JSON.stringify(text)}))?.click()`);settle(); };
const nav = text => { evaluate(`document.querySelector('button[aria-label="Ẩn hiện menu"]').click()`);settle();click('aside nav button',text); };
const assertion = (js, message) => { const result = evaluate(`Boolean(${js})`); assert.equal(result,'true',message); console.log('PASS',message); };
const fill = (selector,value) => { run('fill',selector,String(value));settle(); };
const field = (type,index,value) => { evaluate(`(()=>{const e=document.querySelectorAll('form input[type="${type}"]')[${index}];Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(e,${JSON.stringify(value)});e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}));})()`);settle(); };
if (process.argv[2] === 'inspect') { console.log(run('snapshot','-i')); console.log(evaluate(`JSON.stringify({text:document.body.innerText.slice(-3000),fields:Array.from(document.querySelectorAll('form input')).map(e=>({value:e.value,validation:e.validationMessage})), data:localStorage.getItem('son_ngoc_hotel_data_v3')})`)); process.exit(0); }
run('close');
run('open','http://localhost:3000');settle();
loginBrowser(run);
writeFileSync('.review/console-before.json',run('--json','errors'));
evaluate(`(async()=>{ const m=await import('/src/data/initialData.ts'); const room={...m.INITIAL_ROOMS[1],id:'qa-room',number:'QA01',status:'AVAILABLE',cleanStatus:'CLEAN',allowsHourly:true,pricePerHour:100000,pricePerNight:450000,defaultCheckInTime:'16:00',defaultCheckOutTime:'10:00'}; localStorage.setItem('son_ngoc_hotel_data_v3',JSON.stringify({version:3,data:{rooms:[room],services:m.INITIAL_SERVICES,stays:[],reservations:[],invoices:[],debts:[]}})); return true; })()`);
run('reload');settle();
evaluate(`window.__qaErrors=[];addEventListener('error',e=>window.__qaErrors.push(e.message));addEventListener('unhandledrejection',e=>window.__qaErrors.push(String(e.reason)));window.__qaData=()=>JSON.parse(localStorage.getItem('son_ngoc_hotel_data_v3')).data;`);
// Booking conflicts and cancellation keep the other reservation.
const book = name => {
  evaluate(`document.querySelector('header button[title="Đặt phòng trước cho khách"]').click()`);settle();
  assertion(`document.querySelectorAll('form input[type="time"]')[0].value==='16:00' && document.querySelectorAll('form input[type="time"]')[1].value==='10:00'`, 'booking uses configured room times');
  fill('input[placeholder="VD: Trần Quốc Bảo"]',name);
  fill('input[placeholder="VD: 0988776655"]','0900000000');
  fill('input[aria-label="Tiền cọc đặt phòng (VNĐ)"]',123457);
  evaluate(`document.querySelector('form').requestSubmit()`);settle();
};
book('QA Booking A');
assertion(`window.__qaData().reservations.length===1 && window.__qaData().reservations[0].depositAmount===123457`,'booking is saved with an exact VND deposit');
book('QA Booking B');
assertion(`window.__qaData().reservations.length===1 && document.body.innerText.includes('Trùng lịch')`,'overlapping booking is rejected');
click('form button','Hủy bỏ');
book('QA Booking C');
field('date',0,'2026-12-01');field('date',1,'2026-12-02');
evaluate(`document.querySelector('form').requestSubmit()`);settle();
assertion(`window.__qaData().reservations.length===2`,'non-overlapping booking is accepted');
nav('Đặt phòng');
click('main button','Dạng bảng');
assertion(`document.querySelector('.mobile-table-wide')!==null && document.documentElement.scrollWidth===innerWidth`,'mobile table scroll stays within the page');
evaluate(`document.querySelector('main tbody tr button[title="Hủy đặt phòng này"]').click()`);settle();
click('button','Hủy đặt phòng');
assertion(`window.__qaData().rooms[0].status==='RESERVED' && window.__qaData().reservations.filter(r=>r.status==='CONFIRMED').length===1`,'cancelling one booking keeps the room reserved for the other');
// Check in now, using a start exactly eight hours earlier.
evaluate(`document.querySelector('header button[aria-label="Nhận phòng"]').click()`);settle();
assertion(`document.querySelectorAll('form input[type="time"]')[1].value==='10:00'`, 'check-in uses configured checkout time');
fill('input[placeholder="VD: Nguyễn Hoàng Nam"]','QA Hourly');
fill('input[placeholder="VD: 0912345678"]','0900000000');
click('form button','Theo giờ');
const start = new Date(Date.now()-8*3600000);
const date = new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit'}).format(start);
const time = new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Ho_Chi_Minh',hour:'2-digit',minute:'2-digit',hour12:false}).format(start);
field('date',0,date);field('time',0,time);
fill('input[placeholder="0"]',1000001);
evaluate(`document.querySelector('form').requestSubmit()`);settle();
assertion(`window.__qaData().stays.length===1 && window.__qaData().rooms[0].status==='OCCUPIED'`,'hourly check-in is saved atomically');
run('reload');settle();
evaluate(`window.__qaData=()=>JSON.parse(localStorage.getItem('son_ngoc_hotel_data_v3')).data; window.__qaErrors=[];addEventListener('error',e=>window.__qaErrors.push(e.message));`);
assertion(`window.__qaData().stays[0].customerName==='QA Hourly'`,'check-in persists after reload');
click('main button','QA01');
click('.room-dialog-footer button','Trả phòng');
const plannedEnd = new Date(start.getTime()+8*3600000);
const plannedDate = new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit'}).format(plannedEnd);
const plannedTime = new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Ho_Chi_Minh',hour:'2-digit',minute:'2-digit',hour12:false}).format(plannedEnd);
for (const [label,value] of [['Ngày trả thực tế',plannedDate],['Giờ trả thực tế',plannedTime]]) {
  evaluate(`(()=>{const e=document.querySelector('input[aria-label="${label}"]');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(e,${JSON.stringify(value)});e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}));})()`);settle();
}
assertion(`document.body.innerText.includes('Hoàn lại tiền cọc')`,'checkout displays the excess deposit refund');
fill('input[aria-label="Phụ thu (VNĐ)"]',12347);
fill('input[aria-label="Giảm giá (VNĐ)"]',3461);
click('button','Xác nhận thanh toán');
click('button','Xác nhận trả phòng');
assertion(`window.__qaData().invoices.length===1 && window.__qaData().invoices[0].durationNightsOrHours===8 && window.__qaData().invoices[0].roomCharge===800000 && window.__qaData().invoices[0].surcharge===12347 && window.__qaData().invoices[0].discount===3461 && window.__qaData().invoices[0].refundAmount===191115 && window.__qaData().rooms[0].status==='CLEANING'`,'checkout saves exact VND amounts, charges 8 hours, records refund, and moves room to cleaning');
// Direct browser install prompt, with no extra application dialog.
evaluate(`Array.from(document.querySelectorAll('.invoice-dialog button')).find(e=>!e.textContent.trim())?.click()`);settle();
evaluate(`window.__promptCalls=0;const event=new Event('beforeinstallprompt');event.prompt=async()=>{window.__promptCalls++};event.userChoice=Promise.resolve({outcome:'dismissed',platform:'web'});dispatchEvent(event)`);settle();
evaluate(`document.querySelector('button[aria-label="Ẩn hiện menu"]').click()`);settle();
run('click','aside button[aria-label="Cài ứng dụng"]');settle();
assertion(`window.__promptCalls===1 && !document.querySelector('[aria-label="Hướng dẫn cài ứng dụng"]')`,'install button calls the native prompt immediately');
assertion(`window.__qaErrors.length===0`,'business flows have no runtime errors');
writeFileSync('.review/flow-result.json',evaluate(`JSON.stringify(window.__qaData())`));
console.log('All browser business-flow checks passed.');
run('set','device','iPhone 14');
run('reload');settle();
evaluate(`document.querySelector('button[aria-label="Ẩn hiện menu"]').click()`);settle();
run('click','aside button[aria-label="Cài ứng dụng"]');settle();
assertion(`document.querySelector('[aria-label="Hướng dẫn cài ứng dụng"]')?.textContent.includes('Safari trên iPhone')`,'iPhone install button shows Safari home-screen instructions');
