import { writeFileSync } from 'node:fs';
import { INITIAL_ROOMS, INITIAL_SERVICES } from '../src/data/initialData';
import { LOGIN_CREDENTIAL } from '../src/data/loginCredential';
import { FIXED_LOGIN_CREDENTIAL } from '../src/data/fixedLoginCredential';
import { roomDefaults } from '../src/utils/hotelLogic';
import { validateHotelData } from '../src/utils/hotelStorage';

const rooms = INITIAL_ROOMS.map(({ currentStayId: _stay, currentGuestName: _guest, notes: _notes, ...room }) => roomDefaults({ ...room, status: 'AVAILABLE', cleanStatus: 'CLEAN' }));
const data = validateHotelData({ rooms, services: INITIAL_SERVICES, reservations: [], stays: [], invoices: [], debts: [] });
const json = (value: unknown) => `'${JSON.stringify(value).replaceAll("'", "''")}'::jsonb`;
// Existing credentials and hotel records are never overwritten by initialization.
const sql = `-- Generated by npm run supabase:seed. No plaintext passwords or sample guests.\n` +
  `insert into public.hotel_auth(id, primary_credential, fixed_credential) values (true, ${json(LOGIN_CREDENTIAL)}, ${json(FIXED_LOGIN_CREDENTIAL)}) on conflict (id) do nothing;\n` +
  `insert into public.hotel_state(id, data) values (true, ${json(data)}) on conflict (id) do nothing;\n`;
writeFileSync('supabase/seed.sql', sql, 'utf8');
console.log('Prepared supabase/seed.sql: 15 available rooms, service catalog, hashed credentials; no sample guests or invoices.');
